[build]
publish = "public"
command = "cd themes/geekdoc && npm install && npx gulp default && cd ../../ && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "7.23.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.87.0"
